name: Test
on: push
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.2.1
      - name: install dep
        run: npm ci
      - name: lint app
        run: npm run lint
      - name: Test app
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.2.1
      - name: Build
        run: echo Build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.2.1
      - name: Deploy
        run: echo Deploy


