name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4.2.1
      - name: install dep
        run: npm ci
      - name: Test app
        run: npm run test
