name: Print Pull Request Context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]
jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - name: PrintContext
        run: echo "${{ toJSON(github) }}"